replicaCount: 1

image:
  repository: vibrato/techtestapp
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

postgresql:
  enabled: true

  postgresqlUsername: vibrato
  postgresqlDatabase: vibrato
  postgresqlPassword: "v1brat0Rock5"

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
