version: 0.0
os: linux
files:
  - source: scripts/
    destination: /var/TechChallengeApp/scripts
hooks:
  BeforeInstall:
    - location: scripts/login_to_ecr.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
#TODO: AfterAllowTestTraffic -> to curl the healtcheck endpoint
