"DbUser" = "postgres"
"DbPassword" = "t4wiYmfvltk4kPhYJglU"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "serviantechchallenge.c4f83bfpg4ih.ap-southeast-2.rds.amazonaws.com"
"ListenHost" = "localhost"
"ListenPort" = "3000"