"DbUser" = "postgres"
"DbPassword" = ""
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = ""
<<<<<<< HEAD
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"
=======
"ListenHost" = "localhost"
"ListenPort" = "3000"
>>>>>>> 06f395952c1729a379b62c2a021d611f5473ce60
