"DbUser" = "postgres"
"DbPassword" = "changeme"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "techchallenge-rds.cglsfk2o4xiw.us-east-1.rds.amazonaws.com"
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"