name: $(Date:yyyyMMdd).$(Rev:r)


trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
     - doc
     - ReadME.md
parameters:
  artifactsRoot: ''
  deploymentMode: 'Incremental'
  environmentName: ''
  storageName: ''
  serviceConnection: ''
  resourceGroupLocation: 'Australia Southeast'
  resourceGroup: ''
  csmFileLink: ''
  csmParametersFileLink: ''
  subscriptionId: ''

stages:
- stage: PublishArtifacts
  jobs:
  - job: 'PublishArtifacts'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - publish: $(Build.Repository.LocalPath)/Pipelines/Infra
      artifact: drop

- stage: InfraDeploy
  dependsOn: ['PublishArtifacts']
  jobs:
  - deployment: InfraDeploy
    pool:
        vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy ARM templates - ${{ parameters.deploymentMode }}'
            inputs:
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: ${{ parameters.subscriptionId }}
              resourceGroupName: ${{ parameters.resourceGroup }}
              location: ${{ parameters.resourceGroupLocation }}
              csmFile: ${{ parameters.csmFileLink }}
              csmParametersFile: ${{ parameters.csmParametersFileLink }}


            