name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  - name: deploymentMode
    value: 'incremental'
  - name: serviceConnection
    value: 'techappserviceconnection'
  - name: subscriptionId
    value: 'cafbdbed-54ea-4766-abfc-af46b69af45f'
  - name: resourceGroup
    value: 'tech-app-rg'


trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
     - doc
     - ReadME.md

stages:
- stage: Build
  jobs:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM templates'
      inputs:
        azureResourceManagerConnection: '$(serviceConnection)'
        subscriptionId: '$(subscriptionId)'
        resourceGroupName: '$(resourceGroup)'
        location: 'Australia Southeast'
        csmFile: '$(Build.Repository.LocalPath)/Pipelines/Infra/azuredeploy.json'
        csmParametersFile: '$(Build.Repository.LocalPath)/Pipelines/Infra/azuredeploy.parameters.json'
