name: $(Date:yyyyMMdd).$(Rev:r)


trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
     - doc
     - ReadME.md

stages:
- stage: Build
  jobs:
  - job: 'BuildCode'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: ShellScript@2
      displayName: Build Solution
      inputs:
        scriptPath: '$(Build.Repository.LocalPath)/build.sh'
        failOnStandardError: false

    - task: CmdLine@2
      displayName: Run DB Migration and feed data
      inputs:
        script: ./TechChallengeApp updatedb
        workingDirectory: '$(Build.Repository.LocalPath)/dist'
        failOnStderr: false

    - task: Docker@2
      displayName: Build and Push an image to container registry
      inputs:
        command: buildAndPush
        repository: techapp-docker
        Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
        containerRegistry: techappacrserviceconnection
        tags: latest

    - publish: $(Build.Repository.LocalPath)/Pipelines
      artifact: drop

- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: ['Build']
  jobs:
  - deployment: Production
    pool:
        vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: '/deploy/deploy.yaml'
            parameters:
              artifactsRoot: ''
              serviceConnection: ''
              environmentName: 'Prod'
              subscriptionId: ''
              resourceGroup: ''
              csmFileLink: ''
              csmParametersFileLink: ''


  